spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true # sql을 이쁘게 format
        default_batch_fetch_size: 100

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'steadyking-tech-spring-boot-jwt-jun-commerce-secret-steadyking-tech-spring-boot-jwt-jun-commerce'|base64
  secret: c3RlYWR5a2luZy10ZWNoLXNwcmluZy1ib290LWp3dC1qdW4tY29tbWVyY2Utc2VjcmV0LXN0ZWFkeWtpbmctdGVjaC1zcHJpbmctYm9vdC1qd3QtanVuLWNvbW1lcmNlCg==
  token-validity-in-seconds: 86400 # 24시간

logging:
  level:
    org.hibernate.SQL: debug # 바인딩 된 파라미터까지 볼 수 있다.